apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: spring-boot-service-template
  title: Spring Boot Service Template
  description: A template for creating Spring Boot services
  tags:
    - spring
    - java
    - service
spec:
  owner: devops
  type: service
  parameters:
    - title: Service Information
      required:
        - name
        - description
        - package
        - repoUrl
      properties:
        name:
          title: Service Name
          type: string
          description: The name of the Spring Boot service
          ui:autofocus: true
          ui:options:
            rows: 1
        description:
          title: Service Description
          type: string
          description: A brief description of the service
          ui:field: MarkdownField
          ui:widget: textarea
        package:
          title: Package Name
          type: string
          description: The Java package name for the service (e.g., com.company.service)
          default: com.example.service
        javaVersion:
          title: Java Version
          type: string
          enum: ['17', '21']
          default: '21'
        version:
          title: Spring Boot Version
          type: string
          enum: ['3.2.0', '3.4.2']
          default: '3.4.2'
        repoUrl:
          title: Repository URL
          type: string
          description: The GitHub repository URL for the service
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        namespace:
          title: Kubernetes Namespace
          type: string
          description: The Kubernetes namespace to deploy the service to
          default: apps
  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./hello-spring-boot
        values:
          name: '${{ parameters.name }}'
          owner: '${{ parameters.owner }}'
          description: '${{ parameters.description }}'
          repoUrl: '${{ parameters.repoUrl }}'
          namespace: '${{ parameters.namespace }}'
    - id: create-docs-dir
      name: Create docs directory
      action: roadiehq:utils:fs:write
      input:
        path: ./docs/index.md
        content: |
          # ${{ parameters.name }}
          
          This is a Spring Boot service scaffolded from Backstage template.
          
          ## API Endpoints
          
          - `GET /api/hello` - Returns a hello message
          - `GET /actuator/health` - Health check endpoint
          
          ## Running the Service
          
          ```bash
          ./mvnw spring-boot:run
          ```
          
          ## Building
          
          ```bash
          ./mvnw clean package
          ```
          
          ## Docker
          
          The service can be run using Docker:
          
          ```bash
          docker-compose up
          ```
          
          ## Configuration
          
          The service is configured via `application.yml` in the `src/main/resources` directory.
    - id: create-argocd-json
      name: Create ArgoCD Config File
      action: roadiehq:utils:fs:write
      input:
        path: ./argocd-config/${{ parameters.name }}.json
        content: |
          {
            "name": "${{ parameters.name }}",
            "repoUrl": "https://github.com/${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}.git",
            "appPath": "k8s",
            "namespace": "${{ parameters.namespace }}"
          }
    - id: publish
      name: Publish
      action: publish:github
      input:
        description: '${{ parameters.description }}'
        repoUrl: '${{ parameters.repoUrl }}'
    - id: create-argocd-config
      name: Create ArgoCD Config
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=felipeazv&repo=backstage-spotify
        branchName: add-argocd-${{ parameters.name }}
        title: "Add ArgoCD config for ${{ parameters.name }}"
        description: |
          Auto-generated ArgoCD configuration from Backstage scaffolder.
          
          This PR adds the ArgoCD application config for `${{ parameters.name }}`.
        commitMessage: "feat: add ArgoCD config for ${{ parameters.name }}"
        targetPath: argocd/apps
        sourcePath: ./argocd-config
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '${{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: Repository
        url: '${{ steps.publish.output.remoteUrl }}'
      - title: ArgoCD Config PR
        url: '${{ steps["create-argocd-config"].output.pullRequestUrl }}'
      - title: Open in catalog
        icon: catalog
        entityRef: '${{ steps.register.output.entityRef }}'
