---
# ConfigMap for Backstage application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage-spotify
data:
  app-config.yaml: |
    app:
      title: Scaffolded Backstage App
      baseUrl: http://localhost:3000

    organization:
      name: My Company

    backend:
      baseUrl: http://localhost:7007
      listen:
        port: 7007
      csp:
        connect-src: ["'self'", 'http:', 'https:']
      cors:
        origin: http://localhost:3000
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
        allowedHeaders: ['X-Requested-With', 'Content-Type', 'Authorization']
      database:
        client: better-sqlite3
        connection: ':memory:'
      workingDirectory: /app

    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}

    proxy:
      endpoints:
        '/test':
          target: 'https://example.com'
          changeOrigin: true

    techdocs:
      builder: 'local'
      generator:
        runIn: 'docker'
      publisher:
        type: 'local'

    auth:
      providers:
        guest: {}

    scaffolder:
      # see https://backstage.io/docs/features/software-templates/configuration for software template options

    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, API, Resource, Location]
      locations:
        - type: file
          target: /app/examples/entities.yaml
        - type: file
          target: /app/examples/template/template.yaml
          rules:
            - allow: [Template]
        - type: file
          target: /app/examples/template/spring-boot-service-template.yaml
          rules:
            - allow: [Template]
        - type: file
          target: /app/examples/org.yaml
          rules:
            - allow: [User, Group]
        - type: file
          target: /app/examples/users/felipe.yaml
          rules:
            - allow: [User]
        - type: url
          target: https://github.com/felipeazv/hello-spring-boot-backstage/blob/main/catalog-info.yaml
          rules:
            - allow: [Component]

    kubernetes:
      # see https://backstage.io/docs/features/kubernetes/configuration for kubernetes configuration options

    permission:
      enabled: true

---
# Service for Backstage application
apiVersion: v1
kind: Service
metadata:
  name: backstage-service
  namespace: backstage-spotify
  labels:
    app: backstage
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: frontend
    - port: 7007
      targetPort: 7007
      protocol: TCP
      name: backend
  selector:
    app: backstage

---
# Deployment for Backstage application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage-spotify
  labels:
    app: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      initContainers:
        - name: setup-app
          image: node:18-alpine
          command: ["sh", "-c"]
          args:
            - |
              # Copy source code from ConfigMap
              mkdir -p /app
              cp -r /source/* /app/
              
              # Install dependencies
              cd /app
              yarn install --frozen-lockfile
          volumeMounts:
            - name: app-source
              mountPath: /source
            - name: app-workspace
              mountPath: /app
      containers:
        - name: backstage
          image: node:18-alpine
          workingDir: /app
          command: ["sh", "-c"]
          args:
            - |
              # Start both frontend and backend in background
              yarn workspace app start &
              yarn workspace backend start
              
              # Keep the container running
              wait
          ports:
            - containerPort: 3000
              name: frontend
            - containerPort: 7007
              name: backend
          env:
            - name: NODE_ENV
              value: "production"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-secrets
                  key: github-token
            - name: APP_CONFIG_backend_database_connection_string
              value: "sqlite3::memory:"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - name: app-workspace
              mountPath: /app
            - name: app-config
              mountPath: /app/app-config.yaml
              subPath: app-config.yaml
          imagePullPolicy: IfNotPresent
      volumes:
        - name: app-source
          configMap:
            name: backstage-source
        - name: app-workspace
          emptyDir: {}
        - name: app-config
          configMap:
            name: backstage-config
            items:
              - key: app-config.yaml
                path: app-config.yaml

---
# Secret for GitHub token (you'll need to create this)
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage-spotify
type: Opaque
stringData:
  github-token: ""  # Add your GitHub token here