apiVersion: v1
kind: Namespace
metadata:
  name: backstage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.yaml: |
    app:
      title: Backstage
      baseUrl: http://localhost:7000
    backend:
      baseUrl: http://localhost:7000
      listen:
        port: 7000
      database:
        client: sqlite3
        connection: ':memory:'
      cors:
        origin: http://localhost:7000
        credentials: true
    techdocs:
      builder: 'external'
      publisher:
        type: 'local'
        local:
          location: /app/dist/static/docs
    catalog:
      locations:
        - type: url
          target: https://github.com/felipeazv/backstage-spotify/blob/main/catalog-info.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - name: backstage
        image: node:18-alpine
        command: ["/bin/sh", "-c"]
        args:
          - apk add --no-cache git yarn && \
            git clone https://github.com/felipeazv/backstage-spotify.git /app && \
            cd /app && \
            yarn install --frozen-lockfile && \
            yarn build && \
            yarn start
        ports:
        - containerPort: 7000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 7000
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 7000
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-service
  namespace: backstage
  labels:
    app: backstage
spec:
  selector:
    app: backstage
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
  type: ClusterIP