apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-spotify
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/felipeazv/backstage-spotify.git
    targetRevision: HEAD
    path: .
    directory:
      include: 'kubernetes-backstage-minikube.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
