apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ values.name }}
  description: {{ values.description }}
  tags:
    - spring-boot
    - java
    - service
  annotations:
    backstage.io/kubernetes-id: {{ values.name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  
